/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package products.management.system.User;

/**
 *
 * @author M38
 */
public class productsDetail extends javax.swing.JFrame {

    /**
     * Creates new form productsDetail
     */
    public productsDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameSP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loaiSP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        giaSP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        soluongSP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        trangthaiSP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(77, 168, 218));

        jLabel1.setBackground(new java.awt.Color(77, 168, 218));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Sản Phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(96, 181, 255));
        jPanel2.setLayout(null);

        nameSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameSP.setForeground(new java.awt.Color(191, 6, 6));
        nameSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameSP.setText("name");
        jPanel2.add(nameSP);
        nameSP.setBounds(330, 40, 147, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên Sản Phẩm");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(330, 0, 147, 40);

        loaiSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loaiSP.setForeground(new java.awt.Color(191, 6, 6));
        loaiSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loaiSP.setText("name");
        jPanel2.add(loaiSP);
        loaiSP.setBounds(330, 120, 147, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Loại");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 80, 147, 40);

        giaSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        giaSP.setForeground(new java.awt.Color(191, 6, 6));
        giaSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        giaSP.setText("name");
        jPanel2.add(giaSP);
        giaSP.setBounds(330, 200, 147, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Giá");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(330, 160, 147, 40);

        soluongSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        soluongSP.setForeground(new java.awt.Color(191, 6, 6));
        soluongSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        soluongSP.setText("name");
        jPanel2.add(soluongSP);
        soluongSP.setBounds(330, 280, 147, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số Lượng");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(330, 240, 147, 40);

        trangthaiSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trangthaiSP.setForeground(new java.awt.Color(191, 6, 6));
        trangthaiSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trangthaiSP.setText("name");
        jPanel2.add(trangthaiSP);
        trangthaiSP.setBounds(330, 370, 147, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Trạng Thái");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(330, 330, 147, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setData(String tenSP, String loai, String gia, String soluong, String trangthai) {
    nameSP.setText(tenSP);
    loaiSP.setText(loai);
    giaSP.setText(gia);
    soluongSP.setText(soluong);
    trangthaiSP.setText(trangthai);
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productsDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productsDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productsDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productsDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productsDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel giaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loaiSP;
    private javax.swing.JLabel nameSP;
    private javax.swing.JLabel soluongSP;
    private javax.swing.JLabel trangthaiSP;
    // End of variables declaration//GEN-END:variables
}
